name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# <-- este bloco precisa ficar aqui (fora do "on:")
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest -q
      - name: Upload JUnit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-pytest-junit
          path: api-tests/reports/pytest-junit.xml
          if-no-files-found: warn

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend-tests/package-lock.json
      - name: Install deps
        working-directory: frontend-tests
        run: npm ci || npm i
      - name: Run Cypress (headless)
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend-tests
          command: npx cypress run
      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend-tests/cypress/videos
          if-no-files-found: ignore
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend-tests/cypress/screenshots
          if-no-files-found: ignore

  api-bdd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api-bdd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Behave (gera Allure e JUnit)
        run: |
          behave -f allure_behave.formatter:AllureFormatter -o reports/allure-results -f pretty || true
          behave -f junit -o reports/junit || true
      - name: Build Allure HTML
        if: always()
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: api-bdd/reports/allure-results
          allure_report:  api-bdd/reports/allure-report
          keep_reports: 1
      - name: Upload Allure results (raw)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-bdd-allure-results
          path: api-bdd/reports/allure-results
          if-no-files-found: ignore
      - name: Upload Allure report (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-bdd-allure-report
          path: api-bdd/reports/allure-report
          if-no-files-found: ignore
      - name: Upload JUnit (BDD)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-bdd-junit
          path: api-bdd/reports/junit
          if-no-files-found: warn

  deploy-allure:
    name: Deploy Allure to GitHub Pages
    needs: [api-bdd]
    if: always()
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: api-bdd/reports/allure-report  # precisa ter um index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
